import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { getServerSession } from '@/lib/session'
import { cn } from '@/lib/styling'
import { SessionProvider } from '@/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default async function RootLayout({ children }: Props) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={cn(inter.className, 'flex min-h-screen flex-col')}>
          {children}
        </body>
      </SessionProvider>
    </html>
  )
}
